# image will be published to ghcr.io/<user>/<name>
name: gnome
description: This is my personal silverblue image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos: 
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - stow
      - gum
      - starship
      - hplip
      - solaar
      - iotop
      - powertop
      - btop
      - bpftop
      - foot

  - from-file: docker.yml
  - from-file: virtualization.yml

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix
        - Hack
        - Meslo
        - RobotoMono
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
  
  - type: justfiles
    include: 
      - myjust.just

  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.slack.Slack
        - io.dbeaver.DBeaverCommunity
        - com.nextcloud.desktopclient.nextcloud
        - org.chromium.Chromium
        - org.telegram.desktop
        - com.spotify.Client
        - com.microsoft.Edge
        - com.discordapp.Discord
        - com.github.tchx84.Flatseal
        - it.mijorus.gearlever
        - io.missioncenter.MissionCenter
        - com.mattjakeman.ExtensionManager

  - type: gnome-extensions
    install:
      - 16 # https://extensions.gnome.org/extension/16/auto-move-windows/
      - 517 # https://extensions.gnome.org/extension/517/caffeine/
      - 1160 # https://extensions.gnome.org/extension/1160/dash-to-panel/
      - 2236 # https://extensions.gnome.org/extension/2236/night-theme-switcher/

  - type: signing

